### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [phramusca/JaMuz-Remote#3]
Hi,

Since this app is GNU GPL v3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by phramusca** [comment]
Hi,
Yes, I have considered it, even tried but without success. 
If someone wants to do it, I'd be glad.
But, remember it is still a beta version. There are some bugs, especially on wifi sync, that I hope to fix (I use the app so I will but when ?)

**Comment by Poussinou** [comment]
Let's wait for the bugfixes, and then we'll open a [RFP](https://gitlab.com/fdroid/rfp/issues) to add your app to F-Droid

**Comment by phramusca** [comment]
Hi,

I am ready to release v0.5.2 on Fdroid. I have followed he guidelines and created a yaml metadata file: https://gitlab.com/phramusca/fdroiddata/-/blob/org.phramusca.jamuz/metadata/org.phramusca.jamuz.yml

Unfortuneatly, build fails : https://gitlab.com/phramusca/fdroiddata/-/jobs/2882514615

And I can't make a pull request, I am receiving error 500.

Could you help ? Thanks

**Comment by Poussinou** [comment]
@izzysoft you have more knowledge than me here, could you please let us know what you think about this? :)

**Comment by IzzySoft** [comment]
@Poussinou not with builds – standard disclaimer: "I'm not a dev"… Eh, but in that case: Hit retry, looks like a network issue (download failed, resulting in a zero-byte file – so "not in gzip format" as not even a gzip header was there). Strange, happens again when retrying. Let's see if I can trick it with a simple update (thus taking "ownership" of the pipeline maybe).

Apart from that: @phramusca please take a look at my comment. The description is far from being sufficient. I strongly suggest establishing [Fastlane](https://gitlab.com/-/snippets/1895688) here – ideally with some screenshots and an icon as well.

PS: Pipeline failed again – and I'm out of ideas…

PPS: WTF? Guess there's an idea:

> The source branch is [43338 commits behind](https://gitlab.com/fdroid/fdroiddata/-/commits/master) the target branch

Whenever you create a new MR, you should make sure to have the latest code. 43k commits behind – a lot has changed since then, maybe even the location of that download. I've just triggered a rebase now, let's see how that goes. Yay, look: 4 pipelines now (how? Yes, one of those 43k commits updated the YAML of the CI configuration in `.gitlab/`). Issuebot triggered successfully. Build running now. Lint succeeded. And all we did was simply using the **latest** code :laughing:

Hint for future MRs:

```bash
cd fdroiddata
git checkout master
git pull upstream master
git checkout -b <MyNewBranch>
# do changes here
fdroid lint <packageNameYouAddedOrModified>
git add <filename>
git commit -m <message>
git push …
```

Don't ever forget line 3 :smile:

PPPS: The current lint error will go away once you've moved summary & description to fastlane. And don't use punctuation in the summary :wink:

```
org.phramusca.jamuz: Summary 'Audio Player synced with JaMuz Desktop.': Punctuation should be avoided
```

Build still failed, I hope I fixed that with my last commit. Good luck then!

**Comment by IzzySoft** [comment]
OK, remaining build errors must be fixed here by you:

```
2022-08-16 17:54:02,568 ERROR: Found Java JAR file at app/libs/beaglebuddy_mp3.jar
2022-08-16 17:54:02,569 ERROR: Found Java JAR file at app/libs/jaudiotagger-2.2.4-SNAPSHOT.jar
2022-08-16 17:54:02,569 ERROR: Found Java JAR file at app/libs/kidsplace_sdk.jar
2022-08-16 17:54:02,570 ERROR: Found usual suspect 'youtube.*android.*player.*api' at app/libs/YouTubeAndroidPlayerApi.jar
2022-08-16 17:54:02,570 ERROR: Found Java JAR file at app/libs/YouTubeAndroidPlayerApi.jar
2022-08-16 17:54:02,571 ERROR: Could not build app org.phramusca.jamuz: Can't build due to 5 errors while scanning
```

**Comment by phramusca** [comment]
Added: https://f-droid.org/en/packages/org.phramusca.jamuz/
